theme: jekyll-theme-cayman
title: John Grundy's publications repository
description: Papers, talks, (old) code, misc docs
safe: false
url: "https://nzjohng.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
- name: generate-sitemap
  uses: cicirello/generate-sitemap@v1.8.1
