theme: jekyll-theme-cayman
title: John Grundy's publications repository
description: Papers, talks, (old) code, misc docs
safe: false
url: "https://nzjohng.github.io" # the base hostname & protocol for your site
baseurl: /publications
fullurl: "https://nzjohng.github.io/publications"
google_analytics: "G-YBYTW63GFN"
plugins:
  - jekyll-sitemap

